### ISSUE TITLE
Adicionar legenda aos botões de navegação do Carrossel de projetos

### ISSUE THREAD

**Issue by GiovaniBiagi** [tech-pro-bem/abre#12]
De acordo [essa mensagem](https://techprobem.slack.com/archives/C0798E6HVL2/p1730320684405459) do nosso time de QA, não temos legenda para esses botões, o que pode gerar problemas de acessibilidade.

Componente em questão:
![Image](https://github.com/user-attachments/assets/af7ba296-997e-419c-bee3-b1808e33b52c)

O objetivo desta tarefa é adicionar as legendas que estão faltando.

**Comment by pdrmenezes** [comment]
QA alinhou com design que não será adicionada a legenda e que não estava faltando, foi uma escolha de design removê-la no mobile
