### ISSUE TITLE
Alterar tamanho do breakpoint do tema

### ISSUE THREAD

**Issue by GiovaniBiagi** [tech-pro-bem/abre#23]
Atualmente estamos considerando 25em no tema. Porém para dispositivos móveis com a tela um pouco maior (475px por ex), o Breakpoint não é aplicado.

Alterar o breakpoint para 57em (912px).

**Comment by pdrmenezes** [comment]
Será que não faz sentido usarmos o mesmo breakpoint que estamos usando em algumas telas, que é o de 40em (±640px)?

Que aí no momento em que o layout for alterado de desktop pra mobile, os tamanhos das fontes também são alterados juntos

**Comment by GiovaniBiagi** [comment]
Acredito que sim @pdrmenezes , podemos usar ele. Não lembro como chegamos nesse valor de 912px, @marcelluscaio lembra?

**Comment by marcelluscaio** [comment]
Foi no olho, mais ou menos metade da minha tela, usando navegador em tela dividida. Podemos usar 40em, e aumentamos se precisar

**Comment by pdrmenezes** [comment]
PR aberto: https://github.com/tech-pro-bem/abre/pull/25
 
- Alteração nesse [commit](https://github.com/tech-pro-bem/abre/pull/25/commits/daf03d2a69490e9165742206218201c57d0658c2)
- o 2º commit é resolvendo conflito com a main
